name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install wasm
        run: rustup target add wasm32-unknown-unknown
      - name: Install trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Run trunk build
        run: ./trunk build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist/
          retention-days: 1
